package com.queue.client.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.queue.client.entry.HostNo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOST_NO".
*/
public class HostNoDao extends AbstractDao<HostNo, Long> {

    public static final String TABLENAME = "HOST_NO";

    /**
     * Properties of entity HostNo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property IP = new Property(1, String.class, "IP", false, "IP");
        public final static Property ShowNo = new Property(2, String.class, "showNo", false, "SHOW_NO");
        public final static Property Remark = new Property(3, String.class, "remark", false, "REMARK");
    }


    public HostNoDao(DaoConfig config) {
        super(config);
    }
    
    public HostNoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOST_NO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: Id
                "\"IP\" TEXT," + // 1: IP
                "\"SHOW_NO\" TEXT," + // 2: showNo
                "\"REMARK\" TEXT);"); // 3: remark
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOST_NO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HostNo entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String IP = entity.getIP();
        if (IP != null) {
            stmt.bindString(2, IP);
        }
 
        String showNo = entity.getShowNo();
        if (showNo != null) {
            stmt.bindString(3, showNo);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(4, remark);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HostNo entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
 
        String IP = entity.getIP();
        if (IP != null) {
            stmt.bindString(2, IP);
        }
 
        String showNo = entity.getShowNo();
        if (showNo != null) {
            stmt.bindString(3, showNo);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(4, remark);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HostNo readEntity(Cursor cursor, int offset) {
        HostNo entity = new HostNo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // IP
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // showNo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // remark
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HostNo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIP(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setShowNo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setRemark(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HostNo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HostNo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HostNo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
